In [5]:
import numpy as np 
A=np.array([[3, 5,  4, -2], [5,  3, 6, -2], [5, 1,  2, -2], [5, -2, -3,  1]])  #Tomando de ejempo esta matriz 4x4 para verificar los resultados del programa
print(A)

[[ 3  5  4 -2]
 [ 5  3  6 -2]
 [ 5  1  2 -2]
 [ 5 -2 -3  1]]


In [2]:
def autoval(M):
  coefs = np.poly(M)  #Calcula los coeficientes del polinomio característico
  pol_carac = np.poly1d(coefs)    #Polinomio característico
  autovalores = pol_carac.roots   #Calcula las raíces del polinomioque son los autovalores
  matriz_auto = np.diag(np.sort(autovalores)) #Orgniza los autovalores de manera ascendente en la matriz 
  return matriz_auto

In [3]:
autoval(A)

array([[-1.99420958-1.96202693j,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        , -1.99420958+1.96202693j,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         2.        +0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        , 10.98841916+0.j        ]])